services:
  planet-backend:
    image: harbor.jaeyoung2.duckdns.org/planet/planet-backend:latest
    container_name: planet-backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - ../.env.planet-backend
    expose:
      - "8080"
    networks:
      - planet_network
    cpus: 1
    mem_limit: 2g
    volumes: # 호스트 경로 → 컨테이너 경로
      - /home/jaeyoung/jenkins_home/workspace/pk-APKA56ROHWDOECDQQLPK.pem:/app/secrets/pk-APKA56ROHWDOECDQQLPK.pem:ro

networks:
  planet_network:
    external: true
  harbor_harbor:
    external: true