logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE   # ???? ?????

frontend:
  origin: http://localhost:5173

cookie:
  domain: ""          # 미설정이면 생략
  same-site: "Lax"
  secure: false
  http-only: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expire-millis: 300000 # 1000 * 60 * 5= 5 minutes
  refresh-token-expire-millis: 3600000 # 1000 * 60 * 60 = 1 hour

spring:
  application:
    name: planet-backend

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_REST_API_KEY}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post # kakao? ?? ?? ?? ?? ???? post??. (?? ???? ?? ??? ??? ????.)
            authorization-grant-type: authorization_code
            scope: # kakao ?? ?? ?? ?? ??? ID ?
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao

        # kakao provider ??
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # ?? ?? ?? ? ???? ??? ????? ?? ??.

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  data:
    redis:
      host: localhost
      port: 6379
