server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: org.phoenix.planet
  configuration:
    map-underscore-to-camel-case: true

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

    region:
      static: ap-northeast-2

s3:
  upload-path:
    member-profile: release/member-profile/
    product-img: release/product-img/
  upload-bucket:
    name: ${S3_BUCKET_NAME}

cloudfront:
  distribution-domain: ${CLOUDFRONT_DISTRIBUTION_DOMAIN}
  key-pair-id: ${CLOUDFRONT_KEY_PAIR_ID}
  private-key-path: ${CLOUDFRONT_PRIVATE_KEY_PATH}

es:
  endpoint: ${ES_ENDPOINT}
  index: "planet_product_1"
  apiKey: ${ES_API_KEY}
  inferenceId: "my-elser"
  defaultSize: 20
