-- auto-generated definition
create table MEMBER_CARD
(
    MEMBER_CARD_ID  NUMBER               not null primary key,
    MEMBER_ID       NUMBER
        constraint FK_MEMBER_CARD_MEMBER references MEMBER,
    CARD_COMPANY_ID NUMBER
        constraint FK_MEMBER_CARD_COMPANY
            references CARD_COMPANY,
    CARD_NUMBER     VARCHAR2(255),
    CREATED_AT      DATE default SYSDATE not null,
    UPDATED_AT      DATE
);

CREATE SEQUENCE SEQ_MEMBER_CARD START WITH 2 INCREMENT BY 1 NOCACHE NOCYCLE;

INSERT INTO MEMBER_CARD(MEMBER_CARD_ID, MEMBER_ID, CARD_COMPANY_ID, CARD_NUMBER)
VALUES (1, 1, 1, '1234123412341234');

commit;