-- ------------------------- 래플 -------------------------
CREATE TABLE RAFFLE
(
    RAFFLE_ID        NUMBER               NOT NULL
        CONSTRAINT PK_RAFFLE PRIMARY KEY,
    ECO_STOCK_ID     NUMBER               NOT NULL,
    PRODUCT_ID       NUMBER               NOT NULL,
    ECO_STOCK_AMOUNT NUMBER               NOT NULL,
    START_DATE       DATE                 NOT NULL,
    END_DATE         DATE                 NOT NULL,
    CREATED_AT       DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT       DATE,

    CONSTRAINT FK_RAFFLE_ECO_STOCK
        FOREIGN KEY (ECO_STOCK_ID)
            REFERENCES ECO_STOCK (ECO_STOCK_ID),

    CONSTRAINT FK_RAFFLE_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
            REFERENCES PRODUCT (PRODUCT_ID)
);
DROP SEQUENCE seq_raffle;
CREATE SEQUENCE seq_raffle START WITH 5 INCREMENT BY 1 NOCACHE NOCYCLE;

INSERT INTO RAFFLE (RAFFLE_ID, ECO_STOCK_ID, ECO_STOCK_AMOUNT, START_DATE, END_DATE,
                    CREATED_AT, UPDATED_AT, PRODUCT_ID)
VALUES (2, 1, 10, DATE '2025-08-25', DATE '2025-09-03', TIMESTAMP '2025-08-25 17:07:11', null, 80);
INSERT INTO RAFFLE (RAFFLE_ID, ECO_STOCK_ID, ECO_STOCK_AMOUNT, START_DATE, END_DATE,
                    CREATED_AT, UPDATED_AT, PRODUCT_ID)
VALUES (3, 1, 5, DATE '2025-08-21', DATE '2025-09-02', TIMESTAMP '2025-08-25 17:32:37', null, 70);
INSERT INTO RAFFLE (RAFFLE_ID, ECO_STOCK_ID, ECO_STOCK_AMOUNT, START_DATE, END_DATE,
                    CREATED_AT, UPDATED_AT, PRODUCT_ID)
VALUES (4, 2, 10, DATE '2025-08-25', DATE '2025-09-01', TIMESTAMP '2025-08-27 19:14:45', null, 50);

-- 래플 기록
CREATE TABLE raffle_history
(
    raffle_history_id NUMBER                        NOT NULL,
    win_status        VARCHAR2(100) default 'N',
    raffle_id         NUMBER                        NOT NULL,
    member_id         NUMBER                        NOT NULL,
    created_at        DATE          DEFAULT SYSDATE NOT NULL,
    updated_at        DATE,
    CONSTRAINT PK_RAFFLE_HISTORY PRIMARY KEY (raffle_history_id),
    CONSTRAINT ck_raffle_history_win_status CHECK (win_status IN ('Y', 'N')),
    CONSTRAINT fk_raffle_history_raffle FOREIGN KEY (raffle_id)
        REFERENCES raffle (raffle_id),
    CONSTRAINT fk_raffle_history_member FOREIGN KEY (member_id)
        REFERENCES member (member_id)
);
DROP SEQUENCE seq_raffle_history;
CREATE SEQUENCE seq_raffle_history START WITH 25 INCREMENT BY 1 NOCACHE NOCYCLE;

INSERT INTO RAFFLE_HISTORY (RAFFLE_HISTORY_ID, WIN_STATUS, RAFFLE_ID, MEMBER_ID, CREATED_AT,
                            UPDATED_AT)
VALUES (24, 'N', 2, 12, TIMESTAMP '2025-09-01 10:55:16', null);
INSERT INTO RAFFLE_HISTORY (RAFFLE_HISTORY_ID, WIN_STATUS, RAFFLE_ID, MEMBER_ID, CREATED_AT,
                            UPDATED_AT)
VALUES (10000012, 'N', 2, 9, TIMESTAMP '2025-08-26 15:37:16', null);
INSERT INTO RAFFLE_HISTORY (RAFFLE_HISTORY_ID, WIN_STATUS, RAFFLE_ID, MEMBER_ID, CREATED_AT,
                            UPDATED_AT)
VALUES (10000013, 'N', 3, 9, TIMESTAMP '2025-08-26 15:37:16', null);
INSERT INTO RAFFLE_HISTORY (RAFFLE_HISTORY_ID, WIN_STATUS, RAFFLE_ID, MEMBER_ID, CREATED_AT,
                            UPDATED_AT)
VALUES (15, 'N', 3, 12, TIMESTAMP '2025-08-29 12:09:32', null);
INSERT INTO RAFFLE_HISTORY (RAFFLE_HISTORY_ID, WIN_STATUS, RAFFLE_ID, MEMBER_ID, CREATED_AT,
                            UPDATED_AT)
VALUES (4, 'N', 2, 1, TIMESTAMP '2025-08-26 15:37:12', null);
INSERT INTO RAFFLE_HISTORY (RAFFLE_HISTORY_ID, WIN_STATUS, RAFFLE_ID, MEMBER_ID, CREATED_AT,
                            UPDATED_AT)
VALUES (5, 'N', 3, 1, TIMESTAMP '2025-08-26 15:37:16', null);
